### ISSUE TITLE
Allow translations for excuses

### ISSUE THREAD

**Issue by Dynnammo** [michelegera/devexcuses-api#24]
As a developer, I would like to send devexcuses to people that aren't english-native speakers.

**Implementation**

- [x] Add i18n setup for the project (`locales` folder with `en.yml`, `es.yml`, `fr.yml` etc.)
- [x] Adding a non-mandatory argument `locale` or `lang` in the API that precises the wanted language of the excuse. If argument is not provided, return a random excuse in english. If it's provided, return it in the desired language.

**Founding/Help**
Not a Rubyist, but quite understand the language + ready to give time on the translation process.

**Comment by michelegera** [comment]
Hey @Dynnammo, thanks for your suggestion! I’ve implemented multilanguage support in #31.

French translations are courtesy of Google Translate and will definitely need a thorough review from a native speaker — would you be willing to help with that?

Thanks!

**Comment by Dynnammo** [comment]
With pleasure

**Comment by michelegera** [comment]
Hey @Dynnammo, not sure if you’ve already started working on this, but I’d like to merge #31 for now – you can then branch it off and add your translation.

Thanks again for your input on this!
