### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by tomdaniels** [michelegera/devexcuses-api#53]
how does cors work with this api? making a fairly simple app that consumes this api but can only get a response from a browser with disabled web secuity. Keep coming up against this error: 
```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

At a guess, I'm thinking the cors [middleware is commented out](https://github.com/michelegera/devexcuses-api/blob/eb22c9d31d8401b8f7e26b1df9d567c605a65654/config/initializers/cors.rb#L4) 🤔

**Comment by michelegera** [comment]
Hey @tomdaniels, thanks for pointing that out 😅 
I just deployed CORS configuration for the API, your app should work now!
